openapi: 3.0.1
paths:
  /hello:
    get:
      operationId: index
      responses:
        "200":
          description: index 200 response
          content:
            application/json:
              schema:
                type: string
