version: 2.1
executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout
      - run: ./gradlew clean build

  test:
    executor: gradle-executor
    steps:
      - checkout
      - run: ./gradlew test

  deploy:
    executor: gradle-executor
    steps:
      - checkout
      - run: ./gradlew publish

  

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
